### ISSUE TITLE
NoSleep

### ISSUE THREAD

**Issue by pr0dukt** [teakhanirons/ftpeverywhere#2]
Any idea how to Deactivate the NoSleep function once you run the .vpk? I like to use it when I'm actively using the vita, but now I can't seem to get my vita to sleep no matter what I set the standby mode timer too, and the Vpk has no UI, it just runs and auto closes. So I can't seem to find a way to disable it. =x

**Comment by teakhanirons** [comment]
Look at the code for Nosleep.vpk here: https://bitbucket.org/SilicaAndPina/nosleep/src/dbed67333fc3c389addedbdaab16776e7f46801c/main.c#lines-14

It's a one-liner.

Sets "/CONFIG/POWER_SAVING" > "suspend_interval" in registry to 0.

I tried looking for the default values listings but I couldn't find it right now. It's %99 30 anyway. Just change it to whatever (preferably 30) using a registry editor and restart, that should fix it.

We mostly hang around in http://discord.cbps.xyz , if you have any other questions.
